#!/bin/sh
bspc rule -r "*"

###---Autostart---###
nm-applet &
xrdb ~/.Xresources &
#/usr/local/bin/scripts/start_polybar.sh &
#killall bspswallow
#pgrep bspswallow || /usr/local/bin/scripts/bspswallow &

###---MONITORS---###
#bspc monitor DP-1-1-8 -d 6 7 8 9 0
#bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
#start_polybar
#next_background 
#/usr/local/bin/scripts/xrandr/bspwm/eDP-1_only.sh

# Check main screen

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier control
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#5e3030"
bspc config presel_feedback_color "#5e81ac"

###---Monitor And Desktop Settings----###
#bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 5
bspc config window_gap 18


###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above

#bspc rule -a Alacritty desktop=^1
bspc rule -a Brave-browser desktop=^2

export _JAVA_AWT_WM_NONREPARENTING=1
